


* Config latex                                                       :ignore:

#+LANGUAGE:french
#+OPTIONS: toc:nil %pour ne pas afficher la tdm avant la page de garde


#+SETUPFILE:Latex/Setupfile/Styleslatex/org-plain-latex.org


#+SETUPFILE:Latex/Setupfile/Pagedegarde/Pagedegarde1/pourpagedegarde1.org



#+Latex_header:\usepackage{lastpage} %les latex header ici



#+BEGIN_EXPORT latex
%chargement de la page de garde
\input{$PWD/Latex/Setupfile/Pagedegarde/Pagedegarde1/pagedegarde1.org}
#+END_EXPORT




#+TOC: headlines 2 % afficher tdm ici, nombre de "sous titre", 3= va jusqu'à titre 3

* Newpage :ignore:
\newpage

* Rappel rapide des méthodes


** Cas général des méthodes

Pour les deux méthodes, le but est le même, trouver une équation avec un nombre de points $n+1$ de la forme :


\[ P(x)= a_0 + a_1x + a_2x^2 + … + a_nx^n  \]




** Méthode de Lagrange




La méthode de Lagrange se base sur la formule suivante :

\[ L(x)=\sum _{i=0}^{n}y_{i}\left(\prod _{i=0,i\neq j}^{n}{\frac {x-x_{j}}{x_{i}-x_{j}}}\right) \]

Que l'on peut aussi écrire sous cette forme :

\[ L(X)=\sum _{i=0}^{n}y_{i}l_{i}(X)} \]

Avec $li$ définie tel que :

\[li = \prod _{i=0,i\neq j}^{n}{\frac {x-x_{j}}{x_{i}-x_{j}}}\right \]



** Méthode de Newton


Pour la méthode de newton, nous devons appliquer cette formule :

\[   N(x)=\sum _{i=0}^{k}a_{i}n_{i}(x)}\]

Où $n$ sont les polynômes de Newton définis de la manière
suivante :

\[ n_{i}(x)=\prod _{0\leq j < i}(x-x_{j})\qquad i=0,\ldots ,n  \]

et $a_i$ les différences divisées définit tel que




#+begin_export latex
\begin{align*}
a_0 &= y_1 \\
    a_1 &= \frac{y_2 - y_1}{x_2 - x_1}\\
    ...\\
    a_k &= \nabla^{k}y_{k+1}\\
    ...\\
    a_{n-1} &= \nabla^{n-1}y_{n}
\end{align*}
#+end_export

#+begin_center
Avec pour $j > i$ ,$\nabla^k y_j = \frac{\nabla^{k-1} y_j - \nabla^{k-1}y_{k}}{x_j - x_{k}}$
#+end_center


Conclusion : Nous devons effectuer cette formule :

\[  N(x)=[y_{0}]+[y_{0},y_{1}](x-x_{0})+\ldots +[y_{0},\ldots ,y_{n}](x-x_{0})\ldots (x-x_{n}).}  \]

* Présentation des programmes commentés

Nous ne mettrons pas l'intégralité du code des différentes résolutions, mais ils sont consultables [[file:lagrange.c][ici pour la méthode de Lagrange]], ainsi qu'[[file:newton.c][ici pour la méthode Newton]].

** Nos structures

Nous avons choisis d'utiliser plusieurs structures pour plusieurs cas :
1. La première, la structure /point/, qui est utilisé partout. En effet, cette structure nous permet de stocker les différents points qui nous sont nécessaire pour trouver un polynôme respectant l'interpolation.
2. Puis, la structure /Maillon/. Cette structure est essentielle pour une chose : former des listes, ce qui nous permet d'ajouter un nombre de points indéfinis au départ, puis d'en rajouter, supprimer, etc, sans perdre de la mémoire.
3. La structure /Liste/, qui est la suite logique de structure /Maillon/.
4. La structure polynôme : celle-ci est particulière, une partie lui est entièrement consacré dans la suite du document.
5. Enfin, même si ce n'est pas vraiment une structure, une fonction s'appelant /transformefloatenpoly/ transforme une liste de points en un tableau, permettant alors d'y accéder plus rapidement et facilement.

*** Listes/Points

Le code pour les listes ainsi que pour les points est trouvable [[file:listePoint.c][ici]].

Pour former un point, nous avons tout simplement besoin d'un x et d'un y associé à celui-ci.
La structure des points est donc la suivante :

#+begin_src C
    
  typedef struct point
  {
    float x;
    float y;
  } point;
    
#+end_src

Puis, nous voulons rassembler ses points en des listes, nous avons donc besoin de deux structures supplémentaires : la structure /Maillon/ et la struture /Liste/. Ces deux structures permettent de structurer nos données, les utiliser, et les afficher dans des graphiques.

#+begin_src C
    
  typedef struct Maillon{
    struct Maillon *suiv;
    point val;
  }Maillon;
    
  typedef struct Liste{
    struct Maillon *first;
  }Liste;
    
    
#+end_src

De plus, les fonctions usuelles des listes sont également créé :
1. /creerListe/
2. /detruireListe/
3. ajouteDebut
4. ajouteFin
5. /afficheListePoints/
6. ListLenght
7. supprDebut
8. supprFin
9. supprValeur
10. supprMaillon
11. ListeToTabsPoints, qui transforme une liste en un tableau.
12. ViderListe
   


*** Polynômes

Le code pour les polynôme est trouvable [[file:polynome.c][ici]]. 

Comme vous le savez, le C n'inclue pas de type "polynôme". Nous avons donc dû creer la structure suivante :

#+begin_src C
  
  typedef struct Polynome{
    float *p;
    int maxDeg;
  }polynome;
  
#+end_src

Cette structure à pour but de prendre un tableau, où l'indice du tableau nous permet de trouver le degrès de x, et les valeurs stockés dans le tableau sont les différents coefficients pour chaque x du polynôme.

Nous avons également fait les diverses fonctions de bases :
1. /polynome *creePolynome(int maxDeg)/, qui nous permet de créer un pointeur sur un polynôme.
2. void destroyPolynome(polynome *p), qui supprime un polynôme.
3. void affichepolynome(polynome *p), comme son nom l'indique, affiche le polynôme passé en paramètre.
4. polynome *transformefloatenpoly(float unfloat), qui convertie un flottant en un polynôme.
5. polynome *addPolynome(polynome *p1, polynome *p2), qui nous permet d'additionner (et dans le même temps de soustraire) deux polynôme entre eux

   #+begin_src C
     
     int i;
     polynome *poly =
       creePolynome((p1->maxDeg > p2->maxDeg) ? p1->maxDeg : p2->maxDeg);
     
     for (i = 0; i < p1->maxDeg + 1; ++i)
       {
	 /* printf("Degrèse de p1 %d \n", p1->maxDeg); */
	 poly->p[i] = p1->p[i];
       }
     
     for (i = 0; i < p2->maxDeg + 1; ++i)
       {
	 poly->p[i] += p2->p[i];
       }
     destroyPolynome(p1);
     destroyPolynome(p2);
     return poly;
     
   #+end_src
6. polynome *multPolynome(polynome *p1, polynome *p2). Cette fonction multiplie deux polynômes entre eux.

   #+begin_src C
     
     
     int i, j;
     polynome *poly = creePolynome(p1->maxDeg + p2->maxDeg);
     
     for (i = 0; i < p1->maxDeg + 1; ++i)
       {
	 for (j = 0; j < p2->maxDeg + 1; ++j)
	   {
	     poly->p[i + j] += p1->p[i] * p2->p[j];
	   }
       }
     destroyPolynome(p1);
     destroyPolynome(p2);
     return poly;
     
   #+end_src






** Présentation de la méthode de Lagrange

Pour aborder ce problème, nous avons décidé d'aborder ce problème en deux étapes : 
1. D'abord, calculer Li, avec une fonction /calculLi/
2. Puis, grâce à la fonction /calculLi/ que l'on appelle dans la fonction /calculLagrange/, on renvoie le polynôme correspondant à l'interpolation.

*** Présentation de la fonction /calculLi/

Suite à l'initialisation des variables nécessaires, cette fonction permet le calcul de Li, avec  $i\in [0, 1, ... , k]$.
Les deux principales difficultés sont les suivantes :
1. Prendre en compte le cas de la division par 0, lorsque $x_i - x_j = 0$.
2. Réinitialiser x à chaque tour de boucle. En effet, nos fonction renvoie un nouveau pointeur, ce qui supprime x à chaque fois. Nous devons donc le réinitialiser à chaque tour dans la boucle, ce qui nous permet d'enlever la fameuse erreur "segmentation fault" !

#+begin_src C
  
  for (i = 0; i < ListLenght(points); ++i)
  {
    if (i == numero)
    {
      /* si i = numero, alors il y aurait une division par 0. On ne
	 fait donc rien */
    }
    else
    {
      /* Création du polynôme pour les calculs */
      polynome *x = creePolynome(1);
      x->p[1] = 1;
  
      /* Calcul de la première différence */
      polynome *y = addPolynome(x, transformefloatenpoly(-pointstab[0][i]));
  
      /* calcul de la multiplication par l'inverse de xnum - xi */
      polynome *tmp = multPolynome(
	  y,
	  transformefloatenpoly(1 / (pointstab[0][numero] - pointstab[0][i])));
  
      /* multiplication par le polynôme précédemment calculé */
      Li = multPolynome(Li, tmp);
    }
  }
  
  return Li;
  
#+end_src

*** Présentation de la fonction /calculLagrange/

Cette fonction permet de faire la somme des différents Li trouvé dans la fonction [[*Présentation de la fonction /calculLi/][/calculLi/]].
En effet, pour compléter la méthode de Lagrange, il faut faire une boucle /for/ qui fait une somme des $y_i$ multiplier par [[*Présentation de la fonction /calculLi/][/calculLi/]] pour l'itération $i$.

#+begin_src C
  
    int i;

  /* création du polynôme du résultatde l'interpolation  */
  polynome *fonction = creePolynome(ListLenght(points));

  /* Initialisation d'un tableau à partir d'une liste (accéder au
     valeur plus facilement) */
  float **pointstab;
  pointstab = ListeToTabsPoints(points);

  /* boucle for pour multiplier par yi les Li calculer dans la
     fonction calculLi */
  for (i = 0; i < ListLenght(points); ++i)
  {
    fonction = addPolynome(fonction,
                           multPolynome(transformefloatenpoly(pointstab[1][i]),
                                        calculLi(i, points)));
  }

  return fonction;
  
#+end_src

Il ne reste plus qu'à retourner le polynôme trouver pour pouvoir l'afficher ou bien même l'utiliser dans SDL.

** Présentation de la méthode de Newton


Le code pour l'interpolation newtonienne est disponible [[file:newton.c][ici.]]


Pour la résolution par Newton, nous commençons tout d'abord par initialiser un tableau de la taille adéquate pour nous permettre de stocker les différences divisées.

#+begin_src C
  
  long double **triangle = (long double **)malloc(sizeof(long double *) * (pointNB));
  for(int i = 0; i < pointNB; i++){
    triangle[i] = (long double *)malloc(sizeof(long double) * (pointNB-i));
  }

  
#+end_src

Puis, nous remplissons la première colonne avec les ordonnées des points.

#+begin_src C
for(int i = 0; i < pointNB; i++)  
  {
    triangle[0][i] = Points[1][i];
  }
  
#+end_src

Subséquemment, nous pouvons effectuer le calcul des différences divisées en appliquant la formule du cours

#+begin_src C
  
  for(int i = 1; i < pointNB; i++){
    for(int j = 0; j < pointNB-i; j++){
      triangle[i][j] = (triangle[i-1][j+1] - triangle[i-1][0]) / (Points[0][i+j] - Points[0][i-1]);
    }
   }
  
#+end_src

 
Enfin, nous pouvons passer à la résolution résolution finale, qui elle aussi est issue du cours.
#+begin_src C
  
  for(int i = 0; i < pointNB-1; i++){
    /* créer le polynome "constant" */
    tmp = creePolynome(2);
    tmp->p[1] = 1;
  
    /* résolution de la méthode */
    tmp->p[0] = -Points[0][pointNB - 2 - i];
    Solution = multPolynome(Solution, tmp);
    Solution->p[0] += triangle[pointNB-i-2][0];
  }
  Solution = AdaptePoly(Solution);
  
#+end_src

Il ne nous reste plus qu'à retourner le polynôme obtenu pour pouvoir l'afficher  dans le terminal, où sous une courbe avec SDL.

* Présentation des Jeux d'essais avec commentaires

Les différents résultats sont disponibles en faisant les test grâces au fonctionnalité implémenter dans le programme.


** Densité de l'eau en fonction de la température de l'air :

Liste de points avec une précision de l'ordre de 10^-5.
Difficultés potentielles : précisions.



Résultats : Les deux polynômes sont les mêmes et les calculs sont les bons.



** Les trois séries :

Suites de points normaux.
Difficultés potentielles : aucune, sauf pour le dernier qui ne pourra sûrement pas être calculé (car ce n'est pas une suite de points avec différents $x$)


Résultats : 

  1. Le polynôme est le bon, aucune difficulté

  2. Le polynôme est le bon, mais des erreurs d'approximations sont présentes. Les polynômes ne sont pas exactement les mêmes.

  3. Ne peut pas se calculer : en effet, les points sont sur le même X. L'interpolation est donc incalculable (et infaisable).

     
** Dépenses mensuelles et revenus :

Pour ces données, il y a un grand nombre de données, ainsi qu'un axe des x qui commence avec de "grandes valeurs".

Difficultés potentielles : précisions dû aux résultats importants obtenus.


Résultats :Les polynômes ont soit des coefficients très importants, soit des coefficients presque négligeable. En revanche, on peut constater qu'il y a des approximations de calcul dans les deux méthodes. En effet, les deux polynômes finaux ne sont pas exactement les mêmes, même si ils sont tous les deux du même ordre de grandeur.


** Commentaire global

Pour ses différents jeux d'essais, on peut constater plusieurs choses :

1. L'unicité du polynôme obtenu

   En effet, ce dernier est souvent le même pour les deux méthodes. Évidemment, des approximations de calcul sont présentes.
   
2. Influence de la modification d'un ou plusieurs points donnés sur le polynôme :
   Lorsque l'on donne des points aléatoires au fur et à mesure grâce à l'implémentation de notre méthode "placer un point" pour mettre un point, on peut voir que les deux polynômes s'adaptent bien.

3. Évaluation des coûts :
   Pour Newton, la complexité est de l'ordre (o)n^2, tandis que pour Lagrange, elle est de (o)n^3. 
   Vous pouvez, grâce au programme, afficher les polynômes avec une grande ou une petite précision. Si vous choisissez la méthode précise, vous aurez alors la moyenne des différences avec les points originaux, ce qui nous permet d'avoir une idée précise sur l’efficacité des méthodes.

* Newpage :ignore:
\newpage
* SDL

Le code qui nous permet de gérer la fenêtre SDL est disponible [[file:render.c][ici]].

** Début

Pour démarrer SDL, nous devons initialiser de nombreuses variables, comme par exemple :

- La variable /Stape/, qui nous permet de fermer SDL si elle est égale à 0,
- /size/, qui va nous permettre de gérer la taille de l'écran,
- des variables permettant de garder un nombre d'image par seconde (fps) constant et agréable
- des variables permettant de détecter où le curseur de la souris se trouve sur l'écran
- les varibles permettant de dessiner le graphique
- etc. 




** Affichage et fonctionnalité

*** Affichage

Pour effectuer l'affichage d'une fenêtre SDL, nous devons passer par une boucle /while/.

Puis, nous distinguerons trois cas grâce à un /if/ (et /else if/).

1. Dans le premier cas, SDL dessinera l'écran, s'il n'a pas été dessiné depuis un certain temps
2. Sinon, nous vérifierons également si les courbes sont en adéquation avec les polynômes. Si ce n'est pas le cas, nous entrons alors dans le /else if/ qui va nous permettre d'écraser l'image précédente. Enfin,
3. si nous passons les deux conditions précédentes, nous devons *absolument* endormir le Central Processing Unit (CPU). Cela nous permet de ne pas utiliser tout le processeur de l'ordinateur.

Puis, nous avons aussi un cas de débogage. En effet, si l'on n'est pas entré dans le while depuis une seconde ou plus, il peut y avoir un problème. On recommence alors une seconde "propre", en mettant certaines variables à 0.








*** Fonctionnalités :

Divers fonctionnalités sont présentes :
Vous pouvez afficher la fenêtre grâce à la touche "g". Vous pouvez désormais voir la liste des points, les courbes représentant l'interpolation lagrangienne et newtonienne, ainsi que la liste de points à droite.

De plus, si jamais vous voulez rajouter des points à la liste, cette fonctionnalité est disponible grâce au bouton gauche de la souris. Le bouton droit aura pour effet de supprimer le point sélectionné.

Le curseur aura alors une position (x et y) qui sera automatiquement ajouté dans la liste des points. Les courbes ainsi que les polynômes vont s'adapter automatiquement !


Enfin, vous pouvez zoomer et dézoomer grâce à la molette de la souris.


** Fin de SDL

La fonction /end-sdl/ nous permet de fermet la fenêtre SDL proprement, ainsi que faire les opérations nécessaires pour vider la mémoire qui a besoin d'être libéré.

* Conclusion sur les méthodes

** Site cool : [[https://math-linux.com/mathematiques/interpolation/article/interpolation-polynomiale-de-type-newton-et-differences-divisees][ici]] :noexport: 

** Le reste :ignore:

Nous pourrions sûrement améliorer notre programme pour Newton : en effet, d'après la définition des différences divisées, lorsque l'on ajoute de nouveaux points, nous ne sommes pas obligés de recalculer l'ensemble des coefficients du polynôme.


En revanche, malgré la différence de programme et de méthode utilisé, les méthodes nous amènent au même résultat (hors approximation des calculs). En effet, les polynômes, grâce aux jeux de données, sont trés proches et passent par les différents points donnés (voir fenêtre graphique SDL).





* Annexes  :noexport: 

** Jeux de Test

*** Densité de l'eau

Les résultats obtenus pour Newton sont :

  1.00 +  -0.94*x^(1)  +   1.62*x^(2)  +  -1.21*x^(3)  +   0.53*x^(4)  +  -0.15*x^(5)  +   0.03*x^(6)  +  -0.00*x^(7)  +   0.00*x^(8)  +  -0.00*x^(9)  +   0.00*x^(10)  +  -0.00*x^(11)  +   0.00*x^(12)  +  -0.00*x^(13)  +   0.00*x^(14)  +  -0.00*x^(15)  +   0.00*x^(16)  +  -0.00*x^(17)  +   0.00*x^(18)  +  -0.00*x^(19)
  
Les résultats obtenus pour Lagrange sont :

  1.00 +  -0.94*x^(1)  +   1.62*x^(2)  +  -1.21*x^(3)  +   0.53*x^(4)  +  -0.15*x^(5)  +   0.03*x^(6)  +  -0.00*x^(7)  +   0.00*x^(8)  +  -0.00*x^(9)  +   0.00*x^(10)  +  -0.00*x^(11)  +   0.00*x^(12)  +  -0.00*x^(13)  +   0.00*x^(14)  +  -0.00*x^(15)  +   0.00*x^(16)  +  -0.00*x^(17)  +   0.00*x^(18)  +  -0.00*x^(19)  +   0.00*x^(20) 
  
*** S1


*** S2
*** S3
*** Dépenses mensuelle et revenu
